<!--

    Copyright (c) 2008 by Zetek, Inc.
    All Rights Reserved

-->
<!-- START MASTHEAD CONTAINER -->
<div id="way_mastheadContainer">
<!-- START LOGO CONTAINER -->
<div id ="way_logoContainer" class="floatLeft"><img src="../images/logo_wayfinding.png" width="349" height="55" /></div>
<!-- START LOGO CONTAINER -->
<!-- START GLOBAL NAV CONTAINER -->
<div id="way_globalNavContainer" class="floatRight">
<div id="way_globalNav" class="floatRight alignCenter">
<div id="way_globalNavMenu">
<div id="globalMapLink" class="way_globalNavMenuList"><a href="../client/index.jsp">Maps &amp; Routes</a></div>
<div id="globalAdminLink" class="way_globalNavMenuList marginL25px marginR25px"><a href="../admin/login.jsp">Administration</a></div>
<div id="globalHelpLink" class="way_globalNavMenuList"><a href="https://zetekcorp.com/help/" target="blank">Help</a></div>
</div>
<div id="way_globalNavMapArrow"></div>
<div id="way_globalNavAdminArrow"></div>
<br class="clearFloat" />
</div>
</div>
<!-- END GLOBAL NAV CONTAINER -->
<br class="clearFloat" />
</div>
<!-- END MASTHEAD CONTAINER -->